# Generated by Django 3.1.6 on 2022-04-07 15:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('social_django', '0011_alter_id_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='usersocialauth',
            unique_together={('provider', 'uid', 'user')},
        ),
    ]
